services:
  mysql:
    image: mysql:8
    container_name: registration-with-email-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - mynetwork

  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - mynetwork

  registration-with-email:
    container_name: registration-with-email-application
    build:
      context: ../registration-with-email
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - maildev
    networks:
      - mynetwork

networks:
  mynetwork: